"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import MyProvider from '@/redux/MyProvider'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Navbar from '@/components/Navbar';
import { store } from '@/redux/store'



const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    // <ProviderClient>
    <html lang="en">
      <body className={inter.className}>
        <MyProvider store={store}>
          <Navbar />
          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          {children}
        </MyProvider>
      </body>
    </html>
    // </ProviderClient>
  )
}
